---
title: "R Notebook"
output: html_notebook
---


```{r}
rm(list=ls())
list=ls()
```

```{r, echo=FALSE}
library(dplyr)
library(readxl)
library(caret)
library(scatterplot3d)
```

DATA IMPORTATION:
```{r}
Data_Directory <- "~/Desktop/OSA Case/Regression Notebook/"

setwd(Data_Directory)

train_file <- "train.xlsx"
test_file <- "test.xlsx"

train <- read_excel(paste(Data_Directory, train_file, sep = ""))
test <- read_excel(paste(Data_Directory, test_file, sep = ""))
```

LEARNING PROCESSING:
```{r}
set.seed(1000)
train_Control <- trainControl(method="cv", number=10)
trees <- train(IAH ~ Age+Cervical+BMI, data = train,
               method = "rpart", trControl = train_Control, 
               preProcess = c("center","scale"), tuneLength = 5)

print(trees)
```

```{r}
plot(trees)
```

PREDICTION PROCESS:
```{r}
pred <- predict(trees,newdata=test)
```

METRICS:
```{r}
metrics = postResample(pred, test$IAH)

metrics
```


EXPORT OF DATA:
- import the excel file
```{r, setup, include=FALSE}
Data_Directory <- "~/Desktop/OSA Case/Results/"

knitr::opts_knit$set(root.dir = Data_Directory)

file <- "Regression Results.xlsx"

results <- read_excel(paste(Data_Directory, file, sep = ""))
```

- write into it:
```{r}
results$Decision_Trees = metrics
```

- export the data 
```{r}
write_xlsx(results, paste(Data_Directory, file, sep = ""))
```
