---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list=ls())
list=ls()
```

```{r, echo=FALSE}
library(dplyr)
library(readxl)
library(caret)
library(writexl)
```

DATA IMPORTATION:
```{r, setup, include=FALSE}
Data_Directory <- "~/Desktop/OSA Case/Regression Notebook/"

knitr::opts_knit$set(root.dir = Data_Directory)

setwd(Data_Directory)

train_file <- "train.xlsx"
test_file <- "test.xlsx"

train <- read_excel(paste(Data_Directory, train_file, sep = ""))
test <- read_excel(paste(Data_Directory, test_file, sep = ""))
```

LEARNING AND PREDICTION PROCESS:
```{r}
set.seed(123)
regressor <-  lm(IAH ~ Age+Cervical+BMI, data = train)
regressor
plot(regressor)
summary(regressor)

pred <- predict(regressor, newdata = test)
```

```{r}
summary(regressor)$sigma
summary(regressor)$r.squared
mae_Predict_train <- mean(abs(train$IAH - regressor$fitted.values))
mae_Predict_train
```

```{r}
metrics = postResample(pred, test$IAH)
metrics
```


```{r}
plot(abs(test$IAH-pred),xlab="IAH",type='p',col='blue')
```

```{r}
my_data = as.data.frame(cbind(predicted = pred, observed = test$IAH))

# Plot predictions vs test data
ggplot(my_data,aes(predicted, observed)) + geom_point(color = "darkred", alpha = 0.5) + 
    geom_smooth(method=lm)+ ggtitle('Linear Regression ') + ggtitle("Linear regression: Prediction vs Test Data") +
      xlab("Predecited Power Output ") + ylab("Observed Power Output") + 
        theme(plot.title = element_text(color="darkgreen",size=16,hjust = 0.5),
         axis.text.y = element_text(size=12), axis.text.x = element_text(size=12,hjust=.5),
         axis.title.x = element_text(size=14), axis.title.y = element_text(size=14))
```

EXPORT OF DATA:
- write into a dataframe
```{r}
results <- as.data.frame(metrics)

colnames(results) <- "lm"

results <- as.data.frame(results)
```

- export the data 
```{r, setup, include=FALSE}
Data_Directory <- "~/Desktop/OSA Case/Results/"

knitr::opts_knit$set(root.dir = Data_Directory)

file <- "Regression Results.xlsx"

write_xlsx(results, paste(Data_Directory, file, sep = ""))
```


