---
title: "R Notebook"
output: html_notebook
---


```{r}
rm(list=ls())
list=ls()
```

```{r, echo=FALSE}
library(dplyr)
library(readxl)
library(caret)
```

DATA IMPORTATION:
```{r}
Data_Directory <- "~/Desktop/OSA Case/Regression Notebook/"

setwd(Data_Directory)

train_file <- "train.xlsx"
test_file <- "test.xlsx"

train <- read_excel(paste(Data_Directory, train_file, sep = ""))
test <- read_excel(paste(Data_Directory, test_file, sep = ""))
```

LEARNING PROCESSING:
```{r}
set.seed(123)
train_control <- trainControl(method="cv", number=10)
# ntree couldn't be tune: i did a loop
RMSE = data.frame(matrix(NA,ncol = 10, nrow = 2))
k=1

for (ntree in seq(100,1000,100)) {
	set.seed(40)
	rf <- train(IAH ~ Age+Cervical+BMI, data = train, method = "rf", trControl = train_Control, 
               preProcess = c("center","scale"), ntree=ntree)
	RMSE[,k] = rf$results$RMSE
	k = k+1
}
```

```{r}
RMSE = t(RMSE) #transpose 

matplot(seq(100,1000,100), cbind(RMSE[,1], RMSE[,2]), 
        type = c("l","l"), col = c("steelblue", "steelblue4"), 
        lty = c(1,1),lwd = 3, xlab = "ntrees",ylab = "Accuracy")

legend("bottomright", legend = c("mtry = 2","mtry = 3"), 
       col = c("steelblue", "steelblue4"),pch=20)
```

```{r}
set.seed(56)
rf <- train(IAH ~ Age+Cervical+BMI, data = train,
              method = "rf", trControl = train_control, preProcess = c("center","scale"), ntrees = 200)
rf
```

PREDICTION PROCESS:
```{r}
pred <- predict(rf,newdata=test)
```

METRICS:
```{r}
metrics = postResample(pred, test$IAH)

metrics
```


EXPORT OF DATA:
- import the excel file
```{r, setup, include=FALSE}
Data_Directory <- "~/Desktop/OSA Case/Results/"

knitr::opts_knit$set(root.dir = Data_Directory)

file <- "Regression Results.xlsx"

results <- read_excel(paste(Data_Directory, file, sep = ""))
```

- write into it:
```{r}
results$Random_Forest = metrics
```

- export the data 
```{r}
write_xlsx(results, paste(Data_Directory, file, sep = ""))
```
