---
title: "R Notebook"
output: html_notebook
---


```{r}
rm(list=ls())
list=ls()
```

```{r, echo=FALSE}
library(dplyr)
library(readxl)
library(caret)
library(fastAdaboost)
library(writexl)
```

DATA IMPORTATION:
```{r}
Data_Directory <- "~/Desktop/OSA Case/Classifier Notebook/"

setwd(Data_Directory)

train_file <- "train.xlsx"
test_file <- "test.xlsx"

train <- read_excel(paste(Data_Directory, train_file, sep = ""))
test <- read_excel(paste(Data_Directory, test_file, sep = ""))

test$OSA=factor(test$OSA)
```

LEARNING PROCESSING:
```{r}
set.seed(1000)
train_Control <- trainControl(method="cv", number=10)

ada <- caret::train(OSA ~ Age+Cervical+Gender+BMI, data = train,
               method = "adaboost", trControl = train_Control, 
               preProcess = c("center","scale"))

print(ada)
```

PREDICTION PROCESS:
```{r}
pred <- predict(ada,newdata=test)

```

CONFUSION MATRIX:
```{r}
mat <- caret::confusionMatrix(data=pred,reference=test$OSA,positive="Healthy")

print(mat)
```

ROC CURVE:
```{r}
roc <- roc(test$OSA, as.numeric(pred))
AUC = auc(roc)
```

EXPORT OF DATA:
- import the excel file
```{r, setup, include=FALSE}
Data_Directory <- "~/Desktop/OSA Case/Results/"

knitr::opts_knit$set(root.dir = Data_Directory)

file <- "Classification Results.xlsx"

results <- read_excel(paste(Data_Directory, file, sep = ""))
```

- write into it:
```{r}
results$AdaBoost = c(mat$overall[1], AUC)

```

- export the data 
```{r}
write_xlsx(results, paste(Data_Directory, file, sep = ""))
```