---
title: "R Notebook"
output: html_notebook
---


```{r}
rm(list=ls())
list=ls()
```

```{r, echo=FALSE}
library(dplyr)
library(readxl)
library(writexl)
library(caret)
```

DATA IMPORTATION:
```{r}
Data_Directory <- "~/Desktop/OSA Case/Classifier Notebook/"

setwd(Data_Directory)

Input_file <- "OSA_DB_UPM_2.xlsx"

df_OSA <- read_excel(paste(Data_Directory, Input_file, sep = ""))

df_OSA = as.data.frame(df_OSA)

#df_OSAbis=subset(df_OSA, select = -c(Gender,OSA))
```

DATA SELECTION:
```{r}
df_OSA = df_OSA %>% filter(OSA != "Mild")
#df_OSA = df_OSA %>% filter(Gender!= "mujer")
df_OSA = subset(df_OSA, select = -c(Patient,IAH))
df_OSA$OSA = factor(df_OSA$OSA)
df_OSA$Gender = factor(df_OSA$Gender)
```

CREATION OF THE TEST AND TRAIN SET:
```{r}
trainIndex <- createDataPartition(df_OSA$OSA,p=0.8,list=F)

train <- df_OSA[trainIndex,]
test <- df_OSA[-trainIndex,]

#Check the proportion
print(prop.table(table(df_OSA$OSA)))
print(prop.table(table(test$OSA)))
print(prop.table(table(train$OSA)))
```

```{r}
train_file <- "train.xlsx"
test_file <- "test.xlsx"
train_index <- "index.xlsx"
  
write_xlsx(train, paste(Data_Directory, train_file, sep = ""))
write_xlsx(test, paste(Data_Directory, test_file, sep = ""))
trainIndex <- as.data.frame(trainIndex)
write_xlsx(trainIndex, paste(Data_Directory, train_index, sep = ""))
```

