---
title: "R Notebook"
output: html_notebook
---


```{r}
rm(list=ls())
list=ls()
```

```{r, echo=FALSE}
library(dplyr)
library(readxl)
library(caret)
```

DATA IMPORTATION:
```{r}
Data_Directory <- "~/Desktop/OSA Case/Classifier Notebook/"

setwd(Data_Directory)

train_file <- "train.xlsx"
test_file <- "test.xlsx"

train <- read_excel(paste(Data_Directory, train_file, sep = ""))
test <- read_excel(paste(Data_Directory, test_file, sep = ""))

test$OSA=factor(test$OSA)
```

LEARNING PROCESSING:
```{r}
set.seed(123)
train_Control <- trainControl(method="cv", number=10)
c <- expand.grid(C = seq(0.1,1,0.1)) 

SVM_linear <- train(OSA ~ Age+Cervical+Gender+BMI, data =train,
               method="svmLinear",trControl=train_Control, 
               preProcess= c("center","scale"), tuneGrid = c)

print(SVM_linear)
summary(SVM_linear)

print(SVM_linear$finalModel)
```


```{r}
set.seed(123)
train_Control <- trainControl(method="cv", number=10)

tune <- expand.grid(C = seq(0.2,1,0.1), scale = seq(0.5,1.5,0.25) , degree = 2) 

SVM_poly <- train(OSA ~ Age+Cervical+Gender+BMI, data = train,
               method="svmPoly",trControl=train_Control,
               preProcess= c("center","scale"), tuneGrid = tune)

print(SVM_poly)
summary(SVM_poly)

print(SVM_poly$finalModel)
```


```{r}
set.seed(123)
tune <- expand.grid(C = seq(0.25,0.75,0.1), sigma = seq(0.25,0.75,0.1)) 

SVM_radial <- train(OSA ~ Age+Cervical+Gender+BMI, data =train,
               method="svmRadial",trControl=train_Control, 
               preProcess= c("center","scale"), tuneGrid = tune)

print(SVM_radial)
summary(SVM_radial)

print(SVM_radial$finalModel)
```

PREDICTION PROCESS:
```{r}
pred_linear <- predict(SVM_linear,newdata=test)

pred_poly <- predict(SVM_poly,newdata=test)

pred_radial <- predict(SVM_radial,newdata=test)
```

CONFUSION MATRIX:
```{r}
mat <- confusionMatrix(data=pred_linear,reference=test$OSA,positive="Healthy")

mat1 <- confusionMatrix(data=pred_poly,reference=test$OSA,positive="Healthy")

mat2 <- confusionMatrix(data=pred_radial,reference=test$OSA,positive="Healthy")
```

```{r}
draw_confusion_matrix <- function(cm) {

  layout(matrix(c(1,1,2)))
  par(mar=c(2,2,2,2))
  plot(c(100, 345), c(300, 450), type = "n", xlab="", ylab="", xaxt='n', yaxt='n')
  title('CONFUSION MATRIX', cex.main=2)

  # create the matrix 
  rect(150, 430, 240, 370, col='#3F97D0')
  text(195, 435, 'Class1', cex=1.2)
  rect(250, 430, 340, 370, col='#F7AD50')
  text(295, 435, 'Class2', cex=1.2)
  text(125, 370, 'Predicted', cex=1.3, srt=90, font=2)
  text(245, 450, 'Actual', cex=1.3, font=2)
  rect(150, 305, 240, 365, col='#F7AD50')
  rect(250, 305, 340, 365, col='#3F97D0')
  text(140, 400, 'Class1', cex=1.2, srt=90)
  text(140, 335, 'Class2', cex=1.2, srt=90)

  # add in the cm results 
  res <- as.numeric(cm$table)
  text(195, 400, res[1], cex=1.6, font=2, col='white')
  text(195, 335, res[2], cex=1.6, font=2, col='white')
  text(295, 400, res[3], cex=1.6, font=2, col='white')
  text(295, 335, res[4], cex=1.6, font=2, col='white')

  # add in the specifics 
  plot(c(100, 0), c(100, 0), type = "n", xlab="", ylab="", main = "DETAILS", xaxt='n', yaxt='n')
  text(10, 85, names(cm$byClass[1]), cex=1.2, font=2)
  text(10, 70, round(as.numeric(cm$byClass[1]), 3), cex=1.2)
  text(30, 85, names(cm$byClass[2]), cex=1.2, font=2)
  text(30, 70, round(as.numeric(cm$byClass[2]), 3), cex=1.2)
  text(50, 85, names(cm$byClass[5]), cex=1.2, font=2)
  text(50, 70, round(as.numeric(cm$byClass[5]), 3), cex=1.2)
  text(70, 85, names(cm$byClass[6]), cex=1.2, font=2)
  text(70, 70, round(as.numeric(cm$byClass[6]), 3), cex=1.2)
  text(90, 85, names(cm$byClass[7]), cex=1.2, font=2)
  text(90, 70, round(as.numeric(cm$byClass[7]), 3), cex=1.2)

  # add in the accuracy information 
  text(30, 35, names(cm$overall[1]), cex=1.5, font=2)
  text(30, 20, round(as.numeric(cm$overall[1]), 3), cex=1.4)
  text(70, 35, names(cm$overall[2]), cex=1.5, font=2)
  text(70, 20, round(as.numeric(cm$overall[2]), 3), cex=1.4)
}  
```

```{r}
draw_confusion_matrix(mat)
```

LIFT CURVE:
```{r}
score <- predict(trees,test,type="prob")[,"Severe"]
print(quantile(score))

liftdata <- data.frame(classe=test$OSA)
liftdata$score <- score

lift_obj <- lift(classe ~ score, data=liftdata, class="Severe")
print(lift_obj)
plot(lift_obj)
```


ROC CURVE:
```{r}
roc <- roc(test$OSA, as.numeric(pred_linear))
AUC = auc(roc)

roc1 <- roc(test$OSA, as.numeric(pred_poly))
AUC1 = auc(roc1)

roc2 <- roc(test$OSA, as.numeric(pred_radial))
AUC2 = auc(roc2)
```

```{r}
matplot(1-lift_obj$data$Sp, cbind(lift_obj$data$Sn, 1-lift_obj$data$Sp), type = "l", 
        col = c("steelblue2", "steelblue4"), lwd = 2, xlab = "1 - Specificity",ylab = "Sensitivity", 
        main = "ROC Curve")
legend("bottomright", pch = 15, col="steelblue2", legend=paste("AUC =", round(AUC,3)))
```


EXPORT OF DATA:
- import the excel file
```{r, setup, include=FALSE}
Data_Directory <- "~/Desktop/OSA Case/Results/"

knitr::opts_knit$set(root.dir = Data_Directory)

file <- "Classification Results.xlsx"

results <- read_excel(paste(Data_Directory, file, sep = ""))
```

- write into it:
```{r}
results$SVM_Linear = c(mat$overall[1], AUC)

results$SVM_Poly = c(mat1$overall[1], AUC1)

results$SVM_Radial = c(mat2$overall[1], AUC2)
```

- export the data 
```{r}
write_xlsx(results, paste(Data_Directory, file, sep = ""))
```