---
title: "R Notebook"
output: html_notebook
---


```{r}
rm(list=ls())
list=ls()
```

```{r, echo=FALSE}
library(dplyr)
library(readxl)
library(caret)
library(factoextra)
```

DATA IMPORTATION:
```{r}
Data_Directory <- "~/Desktop/OSA Case/Classifier Notebook/"

setwd(Data_Directory)

Input_file <- "OSA_DB_UPM2.xlsx"

df_OSA <- read_excel(paste(Data_Directory, Input_file, sep = ""))

df_OSA = as.data.frame(df_OSA)
```

DATA PREPARATION:
```{r}
# Study gender separatly
# But the number of female is too low, so I studied only male 
df_OSA = df_OSA %>% filter(OSA != "Mild")
df_OSA_male=subset(df_OSA, Gender=="hombre")
df_OSA_male= subset(df_OSA_male, select = -c(Patient,Gender))
```

PCA: 
```{r}
set.seed(123)
PCA = prcomp(df_OSA_male[,-7], scale=TRUE)
```

```{r}
# Relative influence of each PCA on variance
var=PCA$sdev ^2
relative_var=var/sum(var)
```

```{r}
barplot(relative_var*100, col =  rainbow(6), xlab = "PCA", ylim = c(0,100))
```

SAVE OF PCA1 AND PCA2 INTO A DATAFRAME:
```{r}
df = data.frame(PCA$x[,1], PCA$x[,2])
```


K-MEANS:
```{r}
set.seed(123)
km <- kmeans(df, 2, nstart = 25)
```


```{r}
fviz_cluster(km, data = df,
             palette = c("#2E9FDF", "#00AFBB"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw(),
             main = "K-means"
             )
```

